# Master document
#+OPTIONS: d:nil
# #+PROPERTY: header-args    :exports none
#+LATEX_CLASS: book
#+LaTeX_CLASS_OPTIONS: [a4paper,12pt,oneside]

# #+LATEX_HEADER: \documentclass
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[english]{babel}
#+LATEX_HEADER: \usepackage[a4paper, total={150mm,237mm}, left=30mm, top=30mm,]{geometry}
# #+LATEX_HEADER: \usepackage{fancyhdr}
# #+LATEX_HEADER: \pagestyle{fancyplain}
# #+LATEX_HEADER: \lfoot{Kevin Nolan - kevinn@tcd.ie}
# #+LATEX_HEADER: \rfoot{MMT Thesis 2017}
# #+LATEX_HEADER: \usepackage{empty}
#+LATEX_HEADER: \usepackage{pdfpages}
#+LATEX_HEADER: \usepackage[toc,page]{appendix}
#+LATEX_HEADER: \usepackage{color}
#+LaTeX_HEADER: \usepackage[cache=false]{minted}
#+LATEX_HEADER: \usepackage{caption}
#+LATEX_HEADER: \usepackage{subcaption}
#+LaTeX_HEADER: \linespread{1.3}

#+LaTeX_HEADER: \widowpenalty500
#+LaTeX_HEADER: \clubpenalty500

# #+LaTeX_HEADER: \newminted{common-lisp}{fontsize=\footnotesize}

#+BIBLIOGRAPHY: ../bibliography/mmt-thesis-tidyup.bib

#+PANDOC_OPTIONS: csl:./harvard.csl

# #+PANDOC_OPTIONS: csl:./harvard-durham-university-business-school.csl

# #+PANDOC_OPTIONS: latex-engine:xelatex
#+PANDOC_OPTIONS: latex-engine-opt:-shell-escape
#+PANDOC_OPTIONS: number-sections:t
#+PANDOC_OPTIONS: chapters:t
#+PANDOC_OPTIONS: include-after-body:appendix.tex
#+OPTIONS: toc:nil creator:nil H:4 num:4 ':t ^:{}

# * Front matter                                                       :prelim:
\frontmatter
\pagenumbering{roman} 
\includepdf[pages={1-},scale=1.0]{title-page.pdf}

* Abstract

SonicSketch is a graphic synthesis music tool that runs in the modern web browser and allows users to draw sonic material on a canvas in a freeform, creative and intuitive manner. 

It is aimed at the ideation phase of digital music creation and seeks to highlight the metaphor of sketching instead of the more common analog studio metaphors found in the digital audio workstation (DAW). 

While it takes influence from a number of graphic synthesis systems SonicSketch directly builds on the ideas and concepts of SonicPainter, a separate application created by William Coleman. A critique of this system is given to identify the areas that SonicSketch improves upon.

A detailed account is given of the development process of SonicSketch, including the early prototype work, the architectural setup and the building of the application.

The resulting artifact is evaluated both from a self-assessment and a user perspective. The results of a usability test and general user feedback indicate that it is enjoyable, easy to use and learn.

Finally, a number of proposed improvements and features are given, to make the
application a more flexible and useful tool for musicians.


* Acknowledgments

#+LATEX: \begin{large}
Thanks to my family and friends for all the support throughout the past year, in
particular this last stretch.

Thanks to the MMT staff and lecturers for their tireless dedication. In
particular, thanks to Liam for guiding me through the sometimes stormy waters of
completing this thesis project.

Finally thanks to all my classmates for making this a memorable and enjoyable
year!
#+LATEX: \end{large}


# * Table of Contents                                                  :prelim:

\tableofcontents

\listoffigures

\mainmatter

#+INCLUDE: "./ch-all.org" :minlevel 1


# #+LaTeX: \widowpenalty0
# #+LaTeX: \clubpenalty0
* Bibliography
