* Similar work
:NOTES:
Purpose: trace the alternative history of musical systems (visual music, graphic synthesis)
:END:

** Introduction
:notes:
End with HighC & Coleman to lead into symbolic musical data
:END:

As is pointed out by Levin (2002), the exploration of synchrony between audio
and visuals is a practice going back centuries, being variously termed "ocular
music, visual music, color music, or music for the eyes"
cite:levin_painterly_2000. The twentieth-century technique of the optical
soundtrack, however, brought these ideas to a new level of sophistication. The
technique, which involved placing marks via photography or direct manipulation
to specify audio properties, was explored by such luminaries as Oskar
Fischinger, Norman McLaren and Daphne Oram. Oram's particular take on the
technique will now be discussed as her system most closely resembles that of a
piano roll.

** Sonic sketching from a historical perspective
:NOTES:
    1. Visual music
       1. Oskar Fischinger
       2. Fantasia
    2. Legacy synth systems
       1. Oramics
       2. UPIC
       3. ANS synth
:END:
*** Oramics
A primary motivating factor behind Daphne Oram's development of the Oramic's
machine was to bring more human-like qualities to the sounds generated by
electronic means. The machine worked by playing back multiple lanes of film tape
in unison, defining a monophonic series of notes as well as control signals to
shape their timbre, pitch and amplitude. She details the thought process behind
this in her hugely insightful and broad ranging journal style book, "An
Individual Note" cite:oram_individual_1972.

The aspects of the sound that she wishes to control are volume, duration,
timbre, pitch, vibrato and reverb. In order to do this she describes a simple
musical notation language based on the freehand drawing of lines combined with
discrete symbols. The lines, which she describes as the analog control, are used
to define volume envelopes. Interestingly, the default and preferred method for
the parameters she wishes to control is the continuous line rather than discrete
note symbols. For instance, she avoids the use of a static velocity per note and
instead only specifies the use of a control envelope to change amplitude.

The discrete symbols, which she categorizes as digital control, are used to
define individual pitches and are termed neumes. She highlights that notes
shouldn't remain static and, thusly, an analog control of each note is also
specified. Similarly to amplitude and vibrato, timbre is also defined by the
freehand drawing of lines and is something that with practice the "inner ear"
can develop an intuition as the sonic results of different line shapes. It is
Oram's belief that the hand drawn nature of the lines make the results slightly
inaccurate and to some extent unpredictable but in this also lies the
possibility of bringing more humanity to the cold and precise machines
generating the electronic signal.

** Sonic sketching in the twenty first century
:NOTES:
    1. Golan Levin cite:levin_painterly_2000 
    2. Music animation machine cite:malinowski_music_2017
    3. SonicPainter by William Coleman cite:coleman_sonicpainter:_2015 
    4. Fischinger google doodle
:END:

*** A Golan Levin's AVES
:notes:
 - [ ] Second paragraph needs to be filled out
 
A central tennet to Levin's work was to avoid using randomness. His reasoning that there was already so much information contained within the pen strokes of human input. 

:END:

Golan Levin created the interactive audio visual system, AVES, a series of audio
visual installations in the late nineties and represented a landmark in the
field of visual music. It is an attempt to move away from the diagrammatic
approach to musical interfaces and to present an interface that is painterly in
approach. Taking strong influence from visual artists such as Paul Klee, he
presents a system that maps user input from a graphics tablet and mouse to
visuals and to music. The intention is to create a strong visual correlation
between the visuals and the music. A variety of approaches are taken to achieve
this, all of them involving an algorithmic approach to one degree or another.
For instance, in the piece "Aurora", he maps visuals of a large amount of
particles to a granulated sound synth sound source. He didn't take the approach
of an exact mapping of visual particles to audio particles however and instead
used a statistical control approach to approximate the correlation in between
the visual and aural. cite:levin_painterly_2000

For Levin, the digital pen input in combination with it's infinite variability
represents an ideal instrument for creative expression in his digital temporal
audio visual paintings. cite:snibbe_interactive_2000 The reason he gives for
this is, similar to a musical instrument such as a violin, the pen is instantly
knowable in that a child can pick it up and start creating marks but infinitely
masterable through practice and hard work, and ultimately a vehicle for creative
expression after a certain amount of mastery. A set of criteria that he and John
Maeda arrived at to evaluate the success of their experiments was: is it
instantly knowable, how long did you use it, how much of your personality can be
expressed through it and, finally, with practice is it possible to improve using
it. These ideas foreshadow much of the ideas of the Natural User Interface and
echo principles in game design and music instrument design.

Levin's work is largely realtime and transitional in nature with gestures giving
rise to visual and audio reactions that rise, fall and dissipate. A description
that he uses of some of work is that of creating ripples in a pond. Therefore
his work is very much geared towards an instrument like experience and is not
concerned with the recording or visualization of the temporal unfolding of
musical events as would be the function of compositional tools such as DAWs and
musical notation. Indeed it is a conscious design decision to avoid such
representations. Many of the principles and ideas of his work can, however, be
applied in the context of a composition tool.

*** William Coleman's sonicPainter
SonicPainter by William Coleman is a novel musical sequencer that seeks to
address some of the shortcomings of traditional approaches to music sequencing
found in commercial DAWs cite:coleman_sonicpainter:_2015. The focus of the line
and node based interface (see figure) is to bring timbral shaping to the fore
rather than being hidden away in miscellaneous automation lanes. The design
takes influence from legacy musical systems, in particular, UPIC and
incorporates ideas from visual music and embodied cognition.

Similarly to traditional sequencers the x axis represents time and the y axis
pitch. Note information is input via keyboard and mouse but more as an
intermediary prototype stage. The default mode for input is to click to create a
node and follow that with an additional click to continue to shape the note. The
note can be ended by clicking a keyboard shortcut. By enabling the drawing notes
as lines in this manner, the unfolding of the note can be explicitly represented
visually. Other timbral aspects such as vibrato are represented by further
visual manipulation of the line. For instance, an overlaid sinewave line
indicates the timing and amplitude of the vibrato. In addition, the system
allows for freehand input of notes.

Coleman recommends that the system could be further improved by multitouch
input, specific elements for the control of other synthesis techniques,
time/pitch grid quantization, and further visual timbre feedback
representations. Many of these recommendations will be addressed and explored in
SonicSketch through a system built using the guidelines of NUI (natural user
interface).

    
** Alternative music systems on the web
:NOTES:
 1. Pink trombone - https://dood.al/pinktrombone/
 2. Tonehack
 3. Auraglyph (although not web based)
 4. http://arthurcarabott.com/mui-envelope/
:END:
** Summary of currently available music creation systems 
:NOTES:
(Note that UPIC style sketch synths are not available online)
:END:
** Conclusion 
:NOTES:
Both the twentieth and twenty first century have seen a great deal of
experimentation with ideas of visualizing music and sketching. The audio
processing capabilities available in modern browsers offers an opportunity to
explore and refine less mainstream music creation metaphors.
:END:
